### ISSUE TITLE
Error at [Grabbing dependencies for node packages]

### ISSUE THREAD

**Issue by AhmedAOsman** [chrisl8/ArloBot#23]
I get this error when reaching [Grabbing dependencies for node packages] I tested that on 2 laptops with the same error while using quick install method 

```
bash <(wget -qO- --no-cache https://raw.githubusercontent.com/chrisl8/ArloBot/kinetic/setup-kinetic.sh)
```

```
[Initializing the required Node version]
This is the version I'm developing with now, so stick with it.
v8.4.0 is already installed.
Now using node v8.4.0 (npm v5.3.0)
stable -> 8.4.0 (-> v8.4.0)
default -> 8.4.0 (-> v8.4.0)

[Grabbing dependencies for node packages]
npm WARN deprecated jquery@1.8.3: Versions of the jquery npm package older than 1.9.0 are patched versions that don't work in web browsers. Please upgrade to >=1.11.0.
npm WARN deprecated connect@2.7.2: connect 2.x series is deprecated
/home/ros/.nvm/versions/node/v8.4.0/bin/log.io-server -> /home/ros/.nvm/versions/node/v8.4.0/lib/node_modules/log.io/bin/log.io-server
/home/ros/.nvm/versions/node/v8.4.0/bin/log.io-harvester -> /home/ros/.nvm/versions/node/v8.4.0/lib/node_modules/log.io/bin/log.io-harvester

> contextify@0.1.15 install /home/ros/.nvm/versions/node/v8.4.0/lib/node_modules/log.io/node_modules/contextify
> node-gyp rebuild

make: Entering directory '/home/ros/.nvm/versions/node/v8.4.0/lib/node_modules/log.io/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:
../src/contextify.cc:131:68: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
In file included from /home/ros/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/ros/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/ros/.node-gyp/8.4.0/include/node/v8.h:3792:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/home/ros/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc:150:16: error: ‘class v8::ObjectTemplate’ has no member named ‘SetAccessCheckCallbacks’
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)’:
../src/contextify.cc:182:80: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
In file included from /home/ros/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/ros/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/ros/.node-gyp/8.4.0/include/node/v8.h:3345:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/ros/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)’:
../src/contextify.cc:209:67: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
In file included from /home/ros/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/ros/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/ros/.node-gyp/8.4.0/include/node/v8.h:3345:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/ros/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc:210:71: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
In file included from /home/ros/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/ros/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/ros/.node-gyp/8.4.0/include/node/v8.h:3345:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/ros/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
contextify.target.mk:95: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/home/ros/.nvm/versions/node/v8.4.0/lib/node_modules/log.io/node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ros/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.10.0-37-generic
gyp ERR! command "/home/ros/.nvm/versions/node/v8.4.0/bin/node" "/home/ros/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ros/.nvm/versions/node/v8.4.0/lib/node_modules/log.io/node_modules/contextify
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ros/.npm/_logs/2017-10-28T20_18_15_919Z-debug.log

You will get some errors here. Some are important, some are not.
So far I know the following errors are UNimportant:
'fatal error: libudev.h: No such file or directory'
'Skipping failed optional dependency /chokidar/fsevents'
yarn install v1.2.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.36s.
npm WARN angular-in-memory-web-api@0.2.5 requires a peer of rxjs@^5.0.1 but none was installed.

npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ros/.npm/_logs/2017-10-28T20_18_22_021Z-debug.log

> websockettest@1.0.0 tsc /home/ros/catkin_ws/src/ArloBot/website
> tsc


[Enable non-root use of Bluetooth 4.0.]

[Updating lcars CSS Framework repo]
Already up-to-date.

[Setting up Parallax SimpleIDE for putting code on Activity Board.]
--2017-10-28 22:18:30--  https://web.archive.org/web/20161005174013/http://downloads.parallax.com/plx/software/side/101rc1/simple-ide_1-0-1-rc1_amd64.deb
Resolving web.archive.org (web.archive.org)... 207.241.225.186
Connecting to web.archive.org (web.archive.org)|207.241.225.186|:443... connected.
Unable to establish SSL connection.
dpkg: error processing archive /tmp/simple-ide_1-0-1-rc1_amd64.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 /tmp/simple-ide_1-0-1-rc1_amd64.deb
rm: cannot remove '/tmp/simple-ide_1-0-1-rc1_amd64.deb': No such file or directory

[You must Update your SimpleIDE Learn Folder using the instructions here!]
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at /usr/bin/print line 528.
Error: no such file ":\n\033[0;32mhttp://learn.parallax.com/tutorials/language/propeller-c/propeller-c-set-simpleide/update-your-learn-folder\033[0m\n"

Anytime you want to update ArloBot code from the web you can run this same script again. It will pull down and compile new code without wiping out custom configs in ~/.arlarbot. I run this script myself almost every day.

-----------------------------------
ALL DONE! REBOOT AND START TESTING!
I have a list of tests here: cat /home/ros/catkin_ws/src/ArloBot/manualTests.txt
Look at README.md for testing ideas.
See here for your next step: http://ekpyroticfrood.net/?p=165

```

**Comment by chrisl8** [comment]
All of this should be sorted and corrected now.

**Comment by ahmediv** [comment]
Thank you for your great effort
